name: Automated Commit

on:
  schedule:
    - cron: "0 */12 * * *"  # Má»—i 12 giá» cháº¡y 1 láº§n
  workflow_dispatch:  # Cho phÃ©p cháº¡y báº±ng tay

permissions:
  contents: write

jobs:
  update_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "mztdodo"
          git config user.email "mztadodo@gmail.com"  # thay báº±ng email commit cá»§a báº¡n

      - name: Update timestamp
        run: echo "Last updated: $(date)" > TIMESTAMP.txt

      - name: Commit and push changes
        run: |
          git add TIMESTAMP.txt
          git diff --cached --quiet || git commit -m "ðŸ¤– Auto update timestamp"
          git push
